dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh | bash
notifications:
  slack:
    rooms:
      secure: Dy4ZM2QIhWbF4K4Z7Os616Asg79w8CdCMQr5hAj+IL9QkPxwuTZ1kvPYUNV+fkBWMzgBG1H92iI86ZsPb7S3xMdwUbkVMc0JNFNFnv25Et2Ev1uXFvvaV4urt2ivgVOWLfvrZi/v9l8l6+hBp7IvYQW4UQCMzGRpKm1FDN9dmeZfjARGJ7SUgXV6xpV5VxdDh7XQfiUjD1WAtEJzHON0mbOAKsJ/VrFyyL3pIr0QHtD6Owq0ei7TstS3rxSVDdhu3Pppktcr4W033mLjYamCjF9+bnHpnGu1s/acQHmTcCCZ2qOJo+fGNkirHzxrwPOXhX3auhUmuLL56r4/D+lmAFTcCcmts/eb09s14y0gGrahhpa2l6lg63HeVtJ4vMK8343XSN589mKrRFhAoek0Qa6k06Aaw5cTzXDEcdIFg//m08KsSIx+hBJZcwiGn/8du0LFy8V6JnMVIWNyyXJh3LVnakpVxydOXb0s+r8CdQ473NKqtNUzwyhk1inW3vQjBL86XToXlEsexqdp8/WjojP5srwj8UDyQUx90ljF17JY/gbTbWg7cYFLvTQj/llXpyS/6ELya1KsXt9TMQYspExLNdYyehqpVff9/44+rc9wmyftL9NpWRcr0w2b7HpAKRGS/dAXMibg2fY+5lpkDEXotoPhbLl+/Mng8VpAUBI=
